piface_user:
    resource: "@PifaceUserBundle/Resources/config/routing.yml"
    prefix:   /

piface_app:
    resource: "@PifaceAppBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
